AppBundle\Entity\Questionnaires:
    type: entity
    table: questionnaires
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        question:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        reponsesPossibles:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: reponses_possibles
        bonneReponse:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: bonne_reponse
    oneToOne:
        idRegle:
            targetEntity: Regles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_regle:
                    referencedColumnName: id
            orphanRemoval: false
        idButin:
            targetEntity: Butins
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_butin:
                    referencedColumnName: id_butin
            orphanRemoval: false
    lifecycleCallbacks: {  }
