AppBundle\Entity\Quetes:
    type: entity
    table: quetes
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        codeCategorie:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: code_categorie
        nbEtapes:
            type: boolean
            nullable: false
            column: nb_etapes
        type:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        difficulte:
            type: boolean
            nullable: false
        masque:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        hautFait:
            type: boolean
            nullable: false
            column: haut_fait
        tempsLimite:
            type: smallint
            nullable: true
            options:
                unsigned: false
            column: temps_limite
    manyToMany:
        regles:
            targetEntity: Regles
            mappedBy: quetes
    lifecycleCallbacks: {  }
