AppBundle\Entity\Regles:
    type: entity
    table: regles
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        intitule:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        synthese:
            type: text
            nullable: false
            options:
                fixed: false
    manyToMany:
        quetes:
            targetEntity: Quetes
            inversedBy: regles
            joinTable:
                name: regles_quetes
                joinColumns:
                    quete:
                        referencedColumnName: id
                inverseJoinColumns:
                    regle:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
