AppBundle\Entity\Terminologie:
    type: entity
    table: terminologie
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        terme:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        definition:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        liens:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    oneToOne:
        idRegle:
            targetEntity: Regles
            joinColumns:
                id_regle:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
