<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    // YAML GENERATED CODE

    /**
     * @var string
     */
    private $personnage;

    /**
     * @var string
     */
    private $avatar;

    /**
     * @var boolean
     */
    private $afficher_nom;


    /**
     * Set personnage
     *
     * @param string $personnage
     *
     * @return User
     */
    public function setPersonnage($personnage)
    {
        $this->personnage = $personnage;

        return $this;
    }

    /**
     * Get personnage
     *
     * @return string
     */
    public function getPersonnage()
    {
        return $this->personnage;
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Set afficherNom
     *
     * @param boolean $afficherNom
     *
     * @return User
     */
    public function setAfficherNom($afficherNom)
    {
        $this->afficher_nom = $afficherNom;

        return $this;
    }

    /**
     * Get afficherNom
     *
     * @return boolean
     */
    public function getAfficherNom()
    {
        return $this->afficher_nom;
    }
}
